general:
    name: UPS
    nut_name: UPS
    log_level: 0
    prometheus_exporter:
        enable: true
        port: 9100
    host_checkup:
        interval: 30s
    alerts:
        triggers:
            unexpected_error: true
            host_unreachable: true
            host_connection_fail: true
            ups_status_change: true
            host_turned_off: true
        smtp:
            enabled: false
            host: mail.example.com
            port: 25
            user: from@example.com
            password: PASSWORD
            to_address: to@example.com
        pushover:
            enabled: false
            token: TOKEN
            user: USER
            devices: DEVICE
            priority: 1
        slack:
            enabled: false
            webhook_url: 'https://hooks.slack.com/services/your/slack/URL'
            username: USER
            channel: '#CHANNEL'
            icon: ':sushi:'

hosts:
    esxi.example.com:
        port: 22
        type: unix
        username: USER
        runtime_limit: 10m
        commands:
        - 'poweroff'
    linux.example.com:
        port: 22
        type: unix
        username: USER
        runtime_limit: 5m
        commands:
        - 'shutdown -h'
    windowshost1.example.com:
        type: windows
        username: USER
        password: 
        runtime_limit: 15m
